embedding_model: "BAAI/bge-small-en-v1.5"

classifier_path: "models/classifier.pkl"
vectorizer_path: "models/vectorizer.pkl"
vector_store_path: "models/vector_store.pkl"

llm:
  provider: "gemini"
  model: "gemini-1.5-flash"
  api_key_env: "GEMINI_API_KEY"

api:
  base_url: "http://127.0.0.1:8000"
  enabled: true
  timeout_s: 8
